Voting App/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include,path
from polls import views

urlpatterns = [
    path('polls/',include("polls.urls")),
    path('admin/', admin.site.urls),
    path('home/',views.home,name="home"),   
    path("signin/",views.signin,name="signin"),
    path("signup/",views.signup,name="signup"),
    path("signout/",views.signout,name="signout"),
]

Voting App/mysite/polls/urls.py
from django.urls import path
from . import views
app_name="polls"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

Voting App/mysite/polls/models.py
from django.db import models
import datetime
from django.utils import timezone
from django.contrib import admin
from django.contrib.auth.models import User

# Create your models here.
 
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    @admin.display(
        boolean=True,
        ordering="pub_date",
        description="Published recently?",
    )
    
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now    
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text
def was_published_recently(self):
    now = timezone.now()
    return now - datetime.timedelta(days=1) <= self.pub_date <= now

class uservote(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,null=True, blank=True )
    choice_text = models.ForeignKey(Choice,on_delete=models.CASCADE)
    

Voting App/mysite/polls/views.py
from django.http import HttpResponseRedirect,HttpResponse
from .models import Question,Choice,uservote
from django.shortcuts import get_object_or_404, render,redirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth.models import User

# Create your views here.
class IndexView(generic.ListView):
    template_name = "polls/index.html"
    context_object_name = "latest_question_list"
    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by("-pub_date")[:5]
class DetailView(generic.DetailView):
    model = Question
    template_name = "polls/detail.html"
    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now())
class ResultsView(generic.DetailView):
    model = Question
    template_name = "polls/results.html"

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    print(question)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
        user = User.objects.get(pk=request.user.pk)
        print(user)
        print(selected_choice)
    except (KeyError, Choice.DoesNotExist):
        return render(
            request,
            "polls/detail.html",
            {
                "question": question,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        user_choice = uservote(user=user, choice_text=selected_choice)
        user_choice.save()
        selected_choice.votes+= 1
        selected_choice.save()
        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))
def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    #print(question)
    return render(request, "polls/results.html", {"question": question})


@login_required
def home(request):
    user=request.user.username
    return render(request,'polls/home.html',{'username':user})
def signup(request):
    if request.user.is_authenticated:
        return redirect('home')
    if request.method=="POST":
        form= UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username= form.cleaned_data.get('username')
            password= form.cleaned_data.get('password1')  
            user=authenticate(username=username,password=password)
            login(request,user)
            print(username,password)
            messages.success(request,"Your account is Created Successfully")
            return redirect('home')
        else:
            form=UserCreationForm()
            messages.error(request,"username and password are invalid,Please Try again")
            return render(request,'polls/register.html',{'form':form})     
    else:
        form=UserCreationForm()
        return render(request,'polls/register.html',{'form':form})
def signin(request):
    if request.user.is_authenticated:
        return redirect('home')
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, 'you have loggedin success')
            print(username,password)
            return redirect('home')
        else:
            messages.success(request, 'username and password are invalid,Please Try again')
            return render(request,'polls/signin.html')    
    else:
        return render(request,'polls/signin.html')
def signout(request):
    logout(request)
    return redirect('signin')



    
    

    

Voting App/mysite/polls/templates/polls/detail.html
{% load static %}

<link rel="stylesheet" href="{% static 'polls/style.css' %}">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
<body>
    <nav class="navbar navbar-dark bg-secondary">
        <div class="container-fluid">
            <a class="navbar-brand" href="{%url 'polls:index'%}">Home</a>
        </div>
    </nav>
    <form class="p-4"action="{% url 'polls:vote' question.id %}" method="post">
        {% csrf_token %}
        <fieldset class=>
            <legend><h1>{{ question.question_text }}</h1></legend>
            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
            {% for choice in question.choice_set.all %}
                <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
            {% endfor %}
        </fieldset>
        <br>
        <input type="submit" value="Vote">
    </form>
</body>

Voting App/mysite/polls/templates/polls/home.html
{% load static %}
<link rel="stylesheet" href="{% static 'polls/style.css' %}">
 <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous"> 
 <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script> 
 <link rel="stylesheet" href="{% static 'polls/style.css' %}"/>
<body id="body">
    <nav class="navbar navbar-expand-sm navbar-dark bg-secondary">
        <div class="container-fluid ">
          <a class="navbar-brand">Welcome {{ user.username}}</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
            <ul class="navbar-nav ">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'signout' %}">LOGOUT</a>
              </li>		
            </ul>		  
          </div>
        </div>
      </nav>    
    </nav>
    {%if messages%}
    {%for message in messages%}
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <strong>Hey!</strong> {{message}}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {%endfor%}
    {%endif%}
    <div class="container">
      <h1 style="text-align:center; margin-top:200px; font-weight:bolder"> Vote your Favorite things</h1>
      <br>
      <p style="font-size:30px">Majority rule only works if you're also considering individual rights. Because you can't have five wolves and one sheep voting on what to have for supper.</p>
      <a href="{%url 'polls:index'%}" class="btn btn-primary btn-lg active" role="button" aria-pressed="true" id="but">Play Polls</a>
    </div>
</body>

Voting App/mysite/polls/templates/polls/index.html
{% load static %}
<link rel="stylesheet" href="{% static 'polls/style.css' %}">
 <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous"> 
 <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script> 
 <link rel="stylesheet" href="{% static 'polls/style.css' %}"/>
<body>
    <nav class="navbar navbar-expand-sm navbar-dark bg-secondary">
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a href="{%url 'home'%}"class="nav-link text-white">Home</a>
                </li>   
            </ul>
        </div>       
    </nav>
<br>
<h1>Please Choose any question(s) from below to vote</h1>
<br>
<div class="container ">
    <div class="row">
        {% for question in latest_question_list %}
        <div class="col-sm-6 col-md-4 col-lg-4">
            <div class="card border-dark mb-3 pb-12 " style="max-width: 20rem;">
                <div class="card-header card h-100 ">        
                    <p>{{ question.question_text }}</p>            
                </div>
                <form class="p-4"action="{% url 'polls:vote' question.id %}" method="post">
                    {%csrf_token%}
                    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
                    {% for choice in question.choice_set.all %}
                    <div class="card-body ">
                        <p class="card-text">                   
                            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" required>    
                            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label> 
                            <div class="progress">
                                <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" aria-valuenow="{{choice.votes}}" aria-valuemin="" aria-valuemax="100" style="width: {{choice.votes}}%;">{{choice.votes}}%</div>
                            </div>    
                        </p>
                    </div>
                    {%endfor%}
                    <button type="submit" class="btn btn-primary"><a class="text-decoration-none text-white" href="{% url 'polls:results' question.id %}">Vote </a></button>
                </form>
            </div>
           
        </div>
        {%endfor%}
    </div>
</div>

</body>

Voting App/mysite/polls/templates/polls/register.html
{% load static %}

<link rel="stylesheet" href="{% static 'polls/style.css' %}">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
<link rel="stylesheet" href="{% static 'polls/style.css' %}"/>
<body>
    {%if messages%}
    {%for message in messages%}
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <strong>Hey!</strong> {{message}}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    {%endfor%}
    {%endif%}
    <div class="container">
        <div class="row align-items-center vh-100">
            <div class="col-3 mx-auto">
                <div class="card border-info mb-3" style="max-width: 40rem;"id='card'>
                    <div class="card-header text-center">Create a Secure Account<br> Welcome to Polls App</div>
                        <div class="form">
                            <form class="p-4"action="{% url 'signup' %}" method="post">
                                {% csrf_token %}
                                <div class="card-body ">
                                    <p class="card-text">{{form}}</p>
                                </div>
                                <div class=" d-flex justify-content-center">
                                    <button type="submit" class="btn btn-info ">CREATE ACCOUNT</a></button>
                                </div>    
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <footer class="container" id="foot">
        <a href="{% url 'signin' %}">Already have an account? Login </a>
    </footer>
</body>

Voting App/mysite/polls/templates/polls/results.html
{% load static %}

<link rel="stylesheet" href="{% static 'polls/style.css' %}">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
<nav class="navbar navbar-dark bg-secondary">
    <div class="container-fluid">
        <a class="navbar-brand" href="{%url 'home'%}">Home</a>
    </div>
</nav>
<div class="p-4">
    <h1>Thanks for Voting</h1>

    <br>
    {% for choice in question.choice_set.all %}
    <p><b>{{ choice.choice_text }}</b></p>
    <div class="progress">
        <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" aria-valuenow="{{choice.votes}}" aria-valuemin="" aria-valuemax="100" style="width: {{choice.votes}}%;">{{choice.votes}}%</div>
    </div>
        <br>
    {% endfor %}
    <button type="submit" class="btn btn-primary"><a class="text-decoration-none text-white" href="{% url 'polls:index' %}">Vote again</a></button>


    
</div>    

Voting App/mysite/polls/templates/polls/signin.html
{% load static %}

<link rel="stylesheet" href="{% static 'polls/style.css' %}">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
<body>
    {%if messages%}
    {%for message in messages%}
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <strong>Hey!</strong> {{message}}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {%endfor%}
    {%endif%}
    <div class="container">
        <div class="row align-items-center vh-100">
            <div class="col-3 mx-auto">
                <div class="card border-info mb-3" style="max-width: 20rem;">
                    <div class="card-header text-center">Login to your account</div>
                        <div class="form">
                            <form class="p-4"action="{% url 'signin' %}" method="post">
                                {% csrf_token %}
                                <div class="card-body">
                                    <p class="card-text">
                                        <label for="email" class="font-display">username</label>
                                        <input name="username" class="username"/>
                                        <br>
                                        <label for="password" class="font-display">Password </label>
                                        <br>
                                        <input name="password" type="password" class="password"/>
                                    </p>
                                </div>
                                <div class=" d-flex justify-content-center">
                                    <button class="btn btn-info ">LOG IN</button>
                                </div>   
                            </form>
                        </div>
                    </div>
                    <a class="text-decoration-none text-black" href="{% url 'signup' %}">Don't have an account? Register </a>
                </div>
            </div>
        </div>
        
    </div>
    
</body>